# Testing numpy in Jupyter

In [3]:
import numpy as np

In [4]:
a = np.array(5)
a

array(5)

In [5]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.random.randn(3,4)

array([[ 0.8405094 , -0.10013633, -0.24096775, -0.31982358],
       [-0.41372515,  0.28616378,  0.75062086,  0.04658777],
       [ 0.09640055,  2.22254649, -0.68340826,  0.16152526]])

In [7]:
b = b.reshape(-1, 1)
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
a = np.arange(20)
a = a.reshape(2, 5, 2)
print(a.shape, a.size, a.ndim, a.dtype)

(2, 5, 2) 20 3 int64


In [9]:
c = np.ones((3,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
x = np.array([1, 4, 9, 16, 25])
y= np.arange(5) + np.ones(5)

In [11]:
x + y

array([ 2.,  6., 12., 20., 30.])